version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gnatdb
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
  backend:
    build: ./backend
    command: node src/server.js
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/gnatdb
      JWT_SECRET: supersecret_jwt_change_this
    ports:
      - '4000:4000'
    depends_on:
      - db
    volumes:
      - ./backend/uploads:/app/uploads
  frontend:
    build: ./frontend
    ports:
      - '5173:5173'
    environment:
      VITE_API_URL: http://localhost:4000
    depends_on:
      - backend
volumes:
  db_data:
